print("Tip Calculator")
print("\n")
costMeal = float(input ("Cost of meal: "))
tipPercent = float(input ("Tip percent: "))
tip=round(costMeal*(tipPercent/100),2)
total=round(costMeal+tip,2)
print("\n")
print(f"Tip Amount: {tip}")
print(f"Total Amount: {total}")